# client/constants.py
import struct

# 게임 보드 설정
NUM_ROWS = 10
NUM_COLS = 17
CELL_SIZE = 40      
FONT_SIZE = 15      

# 점수판 너비
SCOREBOARD_WIDTH = 80 

# 채팅창 너비
CHAT_WIDTH = 300    

# 윈도우 너비 계산
WINDOW_WIDTH = (NUM_COLS * CELL_SIZE) + (SCOREBOARD_WIDTH * 2) + CHAT_WIDTH + 30
WINDOW_HEIGHT = (NUM_ROWS * CELL_SIZE) + 120 

# 네트워크 설정
SERVER_IP = "10.125.234.111" 
SERVER_PORT = 8080

CLIENT_SOCKET = None
MY_PLAYER_ID = -1
RECV_THREAD_STARTED = False

# [추가] 현재 실행 중인 홈 화면(로비) 객체를 저장할 변수
CURRENT_HOME_INSTANCE = None

# 통신 프로토콜
PACKET_HEADER_FORMAT = '>IH'
HEADER_SIZE = struct.calcsize(PACKET_HEADER_FORMAT)

OP_CODE = {
    'REQ_LOGIN': 0x0001, 'REQ_QUEUE': 0x0002, 'REQ_REC_CHECK': 0x0003, 
    'REQ_MOVE': 0x0004, 'REQ_CHAT': 0x0006,
    'RES_LOGIN_SUCCESS': 0x0101, 'RES_LOGIN_FAIL': 0x0102,
    'RES_MATCH_SUCCESS': 0x0201, 'NOTI_GAME_UPDATE': 0x0301, 'NOTI_CHAT': 0x0303,
    'START': 'START', 'BOARD': 'BOARD', 'VALID': 'VALID', 
    'INVALID': 'INVALID', 'TURN_CHANGE': 'TURN_CHANGE', 'GAME_OVER': 'GAME_OVER'
}
