# client/constants.py

import struct

# --- 게임 보드 설정 ---
NUM_ROWS = 10
NUM_COLS = 17
CELL_SIZE = 50      
FONT_SIZE = 15      

# UI 레이아웃 크기 설정
SCOREBOARD_WIDTH = 80 
CHAT_WIDTH = 300    

# 윈도우 전체 크기 자동 계산
WINDOW_WIDTH = (NUM_COLS * CELL_SIZE) + (SCOREBOARD_WIDTH * 2) + CHAT_WIDTH + 30
WINDOW_HEIGHT = (NUM_ROWS * CELL_SIZE) + 120 

# --- 네트워크 접속 정보 ---
SERVER_IP = "10.125.234.111" 
SERVER_PORT = 8080

# --- 전역 상태 변수 ---
CLIENT_SOCKET = None
MY_PLAYER_ID = -1
RECV_THREAD_STARTED = False
CURRENT_HOME_INSTANCE = None # 로비 화면 UI 갱신용

# --- 통신 프로토콜 설정 ---
PACKET_HEADER_FORMAT = '>IH'
HEADER_SIZE = struct.calcsize(PACKET_HEADER_FORMAT)

OP_CODE = {
    'REQ_LOGIN': 0x0001, 'REQ_QUEUE': 0x0002, 'REQ_REC_CHECK': 0x0003, 
    'REQ_MOVE': 0x0004, 'REQ_CHAT': 0x0006,
    'RES_LOGIN_SUCCESS': 0x0101, 'RES_LOGIN_FAIL': 0x0102,
    'RES_MATCH_SUCCESS': 0x0201, 'NOTI_GAME_UPDATE': 0x0301, 'NOTI_CHAT': 0x0303,
    'START': 'START', 'BOARD': 'BOARD', 'VALID': 'VALID', 
    'INVALID': 'INVALID', 'TURN_CHANGE': 'TURN_CHANGE', 'GAME_OVER': 'GAME_OVER'
}